
package mp.view;

import java.awt.Toolkit;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import mp.dao.UserDAO;
import mp.model.User;
import mp.model.CommonUser;
import mp.model.VIPUser;

/**
 * Tela de autenticação de usuário
 * 
 * @author Edivânia Pontes (edivaniap@ufrn.edu.br)
 * @author Anne Ílary (ilarymoraes@hotmail.com)
 * @since 18 de junho de 2018
 */
public class JFLogin extends javax.swing.JFrame {

    private UserDAO usuarioDAO;

    /**
     * Creates new form JFLogin
     */
    public JFLogin() {
        initComponents();
        setDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelWelcome = new javax.swing.JLabel();
        jLabelAdm = new javax.swing.JLabel();
        jButtonEnter = new javax.swing.JButton();
        jTextUser = new javax.swing.JTextField();
        jLabelMessage = new javax.swing.JLabel();
        jLabelUser = new javax.swing.JLabel();
        jLabelPass = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jLabelAppTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gem Music Player - Entrar");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp/view/icons/if_gem_big.png"))); // NOI18N

        jLabelWelcome.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabelWelcome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelWelcome.setText("Bem vindo! É a primeira vez que você está aqui!");

        jLabelAdm.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabelAdm.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAdm.setText("Entre com usuario: \"admin\" e senha: \"gemvip\"!");

        jButtonEnter.setBackground(new java.awt.Color(153, 204, 0));
        jButtonEnter.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButtonEnter.setForeground(new java.awt.Color(51, 51, 51));
        jButtonEnter.setText("Entrar");
        jButtonEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnterActionPerformed(evt);
            }
        });

        jTextUser.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jLabelMessage.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabelMessage.setForeground(new java.awt.Color(255, 0, 51));
        jLabelMessage.setText("mensagem...");

        jLabelUser.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelUser.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUser.setText("Usuário");

        jLabelPass.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelPass.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPass.setText("Senha");

        jPasswordField.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jLabelAppTitle.setFont(new java.awt.Font("Maiandra GD", 1, 36)); // NOI18N
        jLabelAppTitle.setForeground(new java.awt.Color(153, 204, 0));
        jLabelAppTitle.setText("Gem Music Player");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabelAppTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelAdm)
                                    .addComponent(jLabelWelcome)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelMessage)
                                    .addComponent(jLabelUser)
                                    .addComponent(jLabelPass)
                                    .addComponent(jPasswordField)
                                    .addComponent(jTextUser)
                                    .addComponent(jButtonEnter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(jLabelLogo)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabelLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAppTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelWelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAdm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabelPass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonEnter)
                .addGap(18, 18, 18)
                .addComponent(jLabelMessage)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnterActionPerformed
        jLabelMessage.setVisible(false);

        if (jTextUser.getText().equals("") || jPasswordField.getText().equals("")) {
            jLabelMessage.setText("Preencha todos os campos");
            jLabelMessage.setVisible(true);
        } else {
            User currentUser = usuarioDAO.authenticate(jTextUser.getText(), jPasswordField.getText());
            if (currentUser != null) {
                try {
                    if(currentUser instanceof VIPUser) {
                        JFVIPPlayer screen = new JFVIPPlayer((VIPUser) currentUser);
                        screen.setVisible(true);
                    } else {
                        JFCommonPlayer screen = new JFCommonPlayer((CommonUser) currentUser);
                        screen.setVisible(true);
                    }
                    this.dispose();
                } catch (IOException ex) {
                    Logger.getLogger(JFLogin.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                jLabelMessage.setText("Dados incorretos");
                jLabelMessage.setVisible(true);
            }
        }
    }//GEN-LAST:event_jButtonEnterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
      
        java.awt.EventQueue.invokeLater(() -> {
            new JFLogin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEnter;
    private javax.swing.JLabel jLabelAdm;
    private javax.swing.JLabel jLabelAppTitle;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JLabel jLabelPass;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JLabel jLabelWelcome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextUser;
    // End of variables declaration//GEN-END:variables

    private void setDetails() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icons/if_gem.png")));
        this.getRootPane().setDefaultButton(jButtonEnter);
        jLabelWelcome.setVisible(false);
        jLabelAdm.setVisible(false);
        jLabelMessage.setVisible(false);
        usuarioDAO = new UserDAO();

        //se ainda não ouver usuários criar um default
        if (usuarioDAO.list().isEmpty()) {
            jLabelWelcome.setVisible(true);
            jLabelAdm.setVisible(true);
            User defaultUser = new VIPUser();
            usuarioDAO.insert(defaultUser);
        }
    }
}
