/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mp.view;

import java.awt.Component;
import java.awt.Toolkit;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import static java.nio.channels.AsynchronousFileChannel.open;
import static java.nio.channels.AsynchronousFileChannel.open;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.Timer;
import mp.dao.MusicaDAO;
import mp.model.Musica;
import mp.model.Usuario;
import mp.sound.MediaPlayer;
import javazoom.jl.player.Player;


/**
 *
 * @author maria
 */
public class JFPlayer extends javax.swing.JFrame {

    DefaultListModel<String> listModel;
    MediaPlayer mediaplayer = null;
    String strPath = null;
    String strName = null;
    String strPlaylist = null;
    MusicaDAO musicaDAO = null;

    /**
     * Creates new form JFPlayer
     */
    public JFPlayer() {
        initComponents();
        setImage();
        loadMusicsOnJlist();
        musicaDAO = new MusicaDAO();
    }

    /**
     * Creates new form JFPlayer
     */
    public JFPlayer(Usuario usuario) {
        initComponents();
        setImage();
        loadMusicsOnJlist();
        musicaDAO = new MusicaDAO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jPanelCentral = new javax.swing.JPanel();
        jLabelPlay = new javax.swing.JLabel();
        jPanelLeft = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListMusicas = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListPlaylists = new javax.swing.JList<>();
        jButtonRemover = new javax.swing.JButton();
        jButtonAddDiretorio = new javax.swing.JButton();
        jButtonAddMusica = new javax.swing.JButton();
        jButtonAddPlaylist = new javax.swing.JButton();
        jPanelRight = new javax.swing.JPanel();
        jButtonAddMusicaPlaylist = new javax.swing.JButton();
        jLabelBack = new javax.swing.JLabel();
        jLabelNext1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        nomePlaylist = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListMusicasPlaylist = new javax.swing.JList<>();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gem Player");
        setBackground(new java.awt.Color(102, 102, 102));
        setFont(new java.awt.Font("Arial Narrow", 0, 10)); // NOI18N
        setResizable(false);

        jPanelCentral.setBackground(new java.awt.Color(255, 255, 255));

        jLabelPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp/view/icons/if_play.png"))); // NOI18N
        jLabelPlay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPlayMouseClicked(evt);
            }
        });

        jPanelLeft.setBackground(new java.awt.Color(0, 0, 51));
        jPanelLeft.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp/view/icons/if_gem_big.png"))); // NOI18N

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 51));

        jListMusicas.setBackground(new java.awt.Color(0, 0, 51));
        jListMusicas.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jListMusicas.setForeground(new java.awt.Color(255, 255, 255));
        jListMusicas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListMusicasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListMusicas);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MÚSICAS");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PLAYLISTS");

        jScrollPane2.setBackground(new java.awt.Color(0, 0, 51));

        jListPlaylists.setBackground(new java.awt.Color(0, 0, 51));
        jListPlaylists.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jListPlaylists.setForeground(new java.awt.Color(255, 255, 255));
        jListPlaylists.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListPlaylistsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jListPlaylists);

        jButtonRemover.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp/view/icons/if_minus.png"))); // NOI18N
        jButtonRemover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverActionPerformed(evt);
            }
        });

        jButtonAddDiretorio.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAddDiretorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp/view/icons/if_add_folder.png"))); // NOI18N
        jButtonAddDiretorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAddDiretorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddDiretorioActionPerformed(evt);
            }
        });

        jButtonAddMusica.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAddMusica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp/view/icons/if_plus.png"))); // NOI18N
        jButtonAddMusica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAddMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddMusicaActionPerformed(evt);
            }
        });

        jButtonAddPlaylist.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAddPlaylist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp/view/icons/if_plus.png"))); // NOI18N
        jButtonAddPlaylist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAddPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddPlaylistActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLeftLayout = new javax.swing.GroupLayout(jPanelLeft);
        jPanelLeft.setLayout(jPanelLeftLayout);
        jPanelLeftLayout.setHorizontalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeftLayout.createSequentialGroup()
                .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLeftLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabelLogo))
                    .addGroup(jPanelLeftLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelLeftLayout.createSequentialGroup()
                                .addComponent(jButtonRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonAddDiretorio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonAddMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonAddPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanelLeftLayout.setVerticalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeftLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabelLogo)
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonRemover)
                        .addComponent(jButtonAddMusica, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jButtonAddDiretorio))
                .addGap(8, 8, 8)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAddPlaylist)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanelRight.setBackground(new java.awt.Color(0, 0, 51));
        jPanelRight.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonAddMusicaPlaylist.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAddMusicaPlaylist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp/view/icons/if_plus.png"))); // NOI18N
        jButtonAddMusicaPlaylist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAddMusicaPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddMusicaPlaylistActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRightLayout = new javax.swing.GroupLayout(jPanelRight);
        jPanelRight.setLayout(jPanelRightLayout);
        jPanelRightLayout.setHorizontalGroup(
            jPanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRightLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAddMusicaPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanelRightLayout.setVerticalGroup(
            jPanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRightLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAddMusicaPlaylist)
                .addGap(143, 143, 143))
        );

        jLabelBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp/view/icons/if_arrow_left.png"))); // NOI18N
        jLabelBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelBack.setPreferredSize(new java.awt.Dimension(64, 64));

        jLabelNext1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp/view/icons/if_arrow_right.png"))); // NOI18N
        jLabelNext1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelNext1.setPreferredSize(new java.awt.Dimension(64, 64));

        nomePlaylist.setBackground(new java.awt.Color(51, 0, 51));
        nomePlaylist.setForeground(new java.awt.Color(51, 0, 51));

        jScrollPane3.setBackground(new java.awt.Color(0, 0, 51));

        jListMusicasPlaylist.setBackground(new java.awt.Color(0, 0, 51));
        jListMusicasPlaylist.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jListMusicasPlaylist.setForeground(new java.awt.Color(255, 255, 255));
        jListMusicasPlaylist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListMusicasPlaylistMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jListMusicasPlaylist);

        javax.swing.GroupLayout jPanelCentralLayout = new javax.swing.GroupLayout(jPanelCentral);
        jPanelCentral.setLayout(jPanelCentralLayout);
        jPanelCentralLayout.setHorizontalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentralLayout.createSequentialGroup()
                .addComponent(jPanelLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCentralLayout.createSequentialGroup()
                        .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCentralLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanelCentralLayout.createSequentialGroup()
                                        .addComponent(jLabelBack, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelPlay)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelNext1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelCentralLayout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(nomePlaylist)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanelCentralLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanelRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelCentralLayout.setVerticalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelRight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCentralLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(nomePlaylist)
                .addGap(80, 80, 80)
                .addComponent(jScrollPane3)
                .addGap(18, 18, 18)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelBack, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNext1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPlay))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jListMusicasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListMusicasMouseClicked

        if (evt.getClickCount() == 2) {
            File musicaFile = new File(strPath);
            mediaplayer = new MediaPlayer(musicaFile);
            mediaplayer.play();
        }
    }//GEN-LAST:event_jListMusicasMouseClicked

    private void jLabelPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPlayMouseClicked

        File musicaFile = new File(strPath);
        MediaPlayer music = new MediaPlayer(musicaFile);

        music.play();
    }//GEN-LAST:event_jLabelPlayMouseClicked

    private void jButtonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverActionPerformed
        //o index vai indicar o numero da linha que deve ser exluida
        int index = jListMusicas.getSelectedIndex();
        musicaDAO.remove(index);
        System.out.println("index sel: " + index);
        loadMusicsOnJlist();
    }//GEN-LAST:event_jButtonRemoverActionPerformed

    private void jButtonAddDiretorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddDiretorioActionPerformed
        JFileChooser fileChooser = new JFileChooser();

        // restringe a amostra a diretorios apenas
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int resposta = fileChooser.showOpenDialog(null);

        if (resposta == JFileChooser.APPROVE_OPTION) {
            File diretorio = fileChooser.getSelectedFile();

            for (File arquivo : diretorio.listFiles()) {
                strName = arquivo.getName();

                //verificar se é arquivo .mp3
                String finalStr = strName.substring(strName.length() - 4, strName.length());
                
                if (finalStr.equals(".mp3")) {
                    strPath = (fileChooser.getSelectedFile().getAbsolutePath() + "\\" + strName);
                    Musica musica = new Musica(strName, strPath);
                    musicaDAO.inserir(musica);
                    
                }
            }

            loadMusicsOnJlist();
        }
    }//GEN-LAST:event_jButtonAddDiretorioActionPerformed

    private void jButtonAddMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddMusicaActionPerformed
        
        JFileChooser open = new JFileChooser();
        int resposta = open.showOpenDialog(null);

        if (resposta == JFileChooser.APPROVE_OPTION) {
            strPath = open.getSelectedFile().getAbsolutePath();
        }
        
        
        strName = strPath.substring(strPath.lastIndexOf(System.getProperty("file.separator")) + 1, strPath.length());
        
        String finalStr = strName.substring(strName.length() - 4, strName.length());
        
        if (finalStr.equals(".mp3")) {          
            Musica musica = new Musica(strName, strPath);
            musicaDAO.inserir(musica);
        }    
            
        loadMusicsOnJlist();
    }//GEN-LAST:event_jButtonAddMusicaActionPerformed

    private void jButtonAddPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddPlaylistActionPerformed
        
       strPlaylist = JOptionPane.showInputDialog("Nomear Playlist");
            
       listModel.addElement(strPlaylist);    
       jListPlaylists.setModel(listModel);
          
    }//GEN-LAST:event_jButtonAddPlaylistActionPerformed

    private void jListPlaylistsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListPlaylistsMouseClicked
        
        nomePlaylist.setText(jListPlaylists.getSelectedValue());
    }//GEN-LAST:event_jListPlaylistsMouseClicked

    private void jButtonAddMusicaPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddMusicaPlaylistActionPerformed
        
        int tamanho = jListMusicas.getModel().getSize();
        Object[] opcoes = new Object[tamanho];
        
        for( int i = 0; i < jListMusicas.getModel().getSize(); i++){
            opcoes[i] = jListMusicas.getModel().getElementAt(i);
        }
        
       Object selecionado =  JOptionPane.showInputDialog(null, "Adicionar musica",
        "Gem Player", JOptionPane.QUESTION_MESSAGE, null, opcoes, null);
        
       String item = (String) selecionado;
       
       listModel.addElement(item);    
       jListMusicasPlaylist.setModel(listModel);

       //remover das opçoes
       // so poder adicionar se tiver uma playlist selecionada
       // vincular essas musicas a essa playlist
    
    }//GEN-LAST:event_jButtonAddMusicaPlaylistActionPerformed

    private void jListMusicasPlaylistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListMusicasPlaylistMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jListMusicasPlaylistMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPlayer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddDiretorio;
    private javax.swing.JButton jButtonAddMusica;
    private javax.swing.JButton jButtonAddMusicaPlaylist;
    private javax.swing.JButton jButtonAddPlaylist;
    private javax.swing.JButton jButtonRemover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelBack;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelNext1;
    private javax.swing.JLabel jLabelPlay;
    private javax.swing.JList<String> jListMusicas;
    private javax.swing.JList<String> jListMusicasPlaylist;
    private javax.swing.JList<String> jListPlaylists;
    private javax.swing.JPanel jPanelCentral;
    private javax.swing.JPanel jPanelLeft;
    private javax.swing.JPanel jPanelRight;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel nomePlaylist;
    // End of variables declaration//GEN-END:variables

    private void setImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icons/if_gem.png")));
    }

    private void loadMusicsOnJlist() {
        musicaDAO = new MusicaDAO();

        ArrayList<Musica> musicas = musicaDAO.listar();
        if (!musicas.isEmpty()) {
            listModel = new DefaultListModel<>();
            DefaultListModel listModel = new DefaultListModel();
            for (Musica m : musicas) {
                listModel.addElement(m.getNome());
            }
            jListMusicas.setModel(listModel);
        }
    }
    
    
}
