/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mp.view;

import java.awt.Toolkit;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import static java.nio.channels.AsynchronousFileChannel.open;
import static java.nio.channels.AsynchronousFileChannel.open;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JList;
import mp.dao.MusicaDAO;
import mp.model.Musica;
import mp.model.Usuario;
import mp.sound.MediaPlayer;

/**
 *
 * @author maria
 */
public class JFPlayer extends javax.swing.JFrame {

    DefaultListModel<String> listModel;
    MediaPlayer mediaplayer = null;
    String strPath = null;
    String strName = null;
    MusicaDAO musicaDAO = null;

    /**
     * Creates new form JFPlayer
     */
    public JFPlayer() {
        initComponents();
        setImage();
        loadMusicsOnJlist();
        musicaDAO = new MusicaDAO();
    }

    /**
     * Creates new form JFPlayer
     */
    public JFPlayer(Usuario usuario) {
        initComponents();
        setImage();
        listModel = new DefaultListModel<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jPanelCentral = new javax.swing.JPanel();
        jLabelPlay = new javax.swing.JLabel();
        jPanelLeft = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListMusicas = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListPlaylists = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jLabelAddMusica = new javax.swing.JLabel();
        jLabelRemoveMusic = new javax.swing.JLabel();
        jLabelAddDiretorio = new javax.swing.JLabel();
        jPanelRight = new javax.swing.JPanel();
        jLabelBack = new javax.swing.JLabel();
        jLabelNext1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gem Player");
        setBackground(new java.awt.Color(102, 102, 102));
        setFont(new java.awt.Font("Arial Narrow", 0, 10)); // NOI18N
        setResizable(false);

        jPanelCentral.setBackground(new java.awt.Color(255, 255, 255));

        jLabelPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp/view/icons/if_play.png"))); // NOI18N
        jLabelPlay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPlayMouseClicked(evt);
            }
        });

        jPanelLeft.setBackground(new java.awt.Color(0, 0, 51));
        jPanelLeft.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp/view/icons/if_gem_big.png"))); // NOI18N

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 51));

        jListMusicas.setBackground(new java.awt.Color(0, 0, 51));
        jListMusicas.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jListMusicas.setForeground(new java.awt.Color(255, 255, 255));
        jListMusicas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListMusicasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListMusicas);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MÚSICAS");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PLAYLISTS");

        jScrollPane2.setBackground(new java.awt.Color(0, 0, 51));

        jListPlaylists.setBackground(new java.awt.Color(0, 0, 51));
        jListPlaylists.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jListPlaylists.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(jListPlaylists);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp/view/icons/if_plus.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelAddMusica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp/view/icons/if_plus.png"))); // NOI18N
        jLabelAddMusica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelAddMusica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAddMusicaMouseClicked(evt);
            }
        });

        jLabelRemoveMusic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp/view/icons/if_minus.png"))); // NOI18N
        jLabelRemoveMusic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelRemoveMusic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRemoveMusicMouseClicked(evt);
            }
        });

        jLabelAddDiretorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp/view/icons/if_add_folder.png"))); // NOI18N
        jLabelAddDiretorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelAddDiretorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAddDiretorioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelLeftLayout = new javax.swing.GroupLayout(jPanelLeft);
        jPanelLeft.setLayout(jPanelLeftLayout);
        jPanelLeftLayout.setHorizontalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeftLayout.createSequentialGroup()
                .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelLeftLayout.createSequentialGroup()
                            .addGap(63, 63, 63)
                            .addComponent(jLabelLogo))
                        .addGroup(jPanelLeftLayout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelLeftLayout.createSequentialGroup()
                                        .addComponent(jLabelRemoveMusic)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelAddDiretorio)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelAddMusica)))))))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanelLeftLayout.setVerticalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeftLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabelLogo)
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAddMusica)
                    .addComponent(jLabelAddDiretorio)
                    .addComponent(jLabelRemoveMusic))
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel3)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jPanelRight.setBackground(new java.awt.Color(0, 0, 51));
        jPanelRight.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanelRightLayout = new javax.swing.GroupLayout(jPanelRight);
        jPanelRight.setLayout(jPanelRightLayout);
        jPanelRightLayout.setHorizontalGroup(
            jPanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 177, Short.MAX_VALUE)
        );
        jPanelRightLayout.setVerticalGroup(
            jPanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabelBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp/view/icons/if_arrow_left.png"))); // NOI18N
        jLabelBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelBack.setPreferredSize(new java.awt.Dimension(64, 64));

        jLabelNext1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp/view/icons/if_arrow_right.png"))); // NOI18N
        jLabelNext1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelNext1.setPreferredSize(new java.awt.Dimension(64, 64));

        javax.swing.GroupLayout jPanelCentralLayout = new javax.swing.GroupLayout(jPanelCentral);
        jPanelCentral.setLayout(jPanelCentralLayout);
        jPanelCentralLayout.setHorizontalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentralLayout.createSequentialGroup()
                .addComponent(jPanelLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelCentralLayout.createSequentialGroup()
                        .addComponent(jLabelBack, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPlay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNext1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jPanelRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelCentralLayout.setVerticalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelRight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCentralLayout.createSequentialGroup()
                .addContainerGap(490, Short.MAX_VALUE)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelBack, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNext1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPlay))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jLabelAddMusicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAddMusicaMouseClicked

        JFileChooser open = new JFileChooser();
        int r = open.showOpenDialog(null);

        if (r == JFileChooser.APPROVE_OPTION) {
            strPath = open.getSelectedFile().getAbsolutePath();
        }

        strName = strPath.substring(strPath.lastIndexOf(System.getProperty("file.separator")) + 1, strPath.length());

        Musica musica = new Musica(strName, strPath);
        musicaDAO.inserir(musica);
        loadMusicsOnJlist();
    }//GEN-LAST:event_jLabelAddMusicaMouseClicked

    private void jListMusicasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListMusicasMouseClicked

        if (evt.getClickCount() == 2) {
            File musicaFile = new File(strPath);
            mediaplayer = new MediaPlayer(musicaFile);
            mediaplayer.play();
        }
    }//GEN-LAST:event_jListMusicasMouseClicked

    private void jLabelRemoveMusicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRemoveMusicMouseClicked
        //o index vai indicar o numero da linha que deve ser exluida
        int index = jListMusicas.getSelectedIndex();
        musicaDAO.remove(index);
        System.out.println("index sel: " + index);
        loadMusicsOnJlist();
    }//GEN-LAST:event_jLabelRemoveMusicMouseClicked

    private void jLabelPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPlayMouseClicked

        File musicaFile = new File(strPath);
        MediaPlayer music = new MediaPlayer(musicaFile);

        music.play();

    }//GEN-LAST:event_jLabelPlayMouseClicked

    private void jLabelAddDiretorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAddDiretorioMouseClicked
//REFAZER COM O PADRAO MVC E SELCIONAR APENAS MP3
        MediaPlayer music = new MediaPlayer(null);
        JFileChooser fc = new JFileChooser();
        // restringe a amostra a diretorios apenas
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int res = fc.showOpenDialog(null);

        if (res == JFileChooser.APPROVE_OPTION) {
            File diretorio = fc.getSelectedFile();
            for (File arquivo : diretorio.listFiles()) {

                strName = arquivo.getName();
                listModel.addElement(strName);
                jListMusicas.setModel(listModel);
                strPath = (fc.getSelectedFile().getAbsolutePath() + "\\" + strName);
                //  music.save(strPath, strName);

            }
        }
    }//GEN-LAST:event_jLabelAddDiretorioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPlayer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelAddDiretorio;
    private javax.swing.JLabel jLabelAddMusica;
    private javax.swing.JLabel jLabelBack;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelNext1;
    private javax.swing.JLabel jLabelPlay;
    private javax.swing.JLabel jLabelRemoveMusic;
    private javax.swing.JList<String> jListMusicas;
    private javax.swing.JList<String> jListPlaylists;
    private javax.swing.JPanel jPanelCentral;
    private javax.swing.JPanel jPanelLeft;
    private javax.swing.JPanel jPanelRight;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

    private void setImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icons/if_gem.png")));
    }

    private void loadMusicsOnJlist() {
        musicaDAO = new MusicaDAO();

        ArrayList<Musica> musicas = musicaDAO.listar();
        if (!musicas.isEmpty()) {
            listModel = new DefaultListModel<>();
            DefaultListModel listModel = new DefaultListModel();
            for (Musica m : musicas) {
                listModel.addElement(m.getNome());
            }
            jListMusicas.setModel(listModel);
        }
    }

}
