package mp.view;

import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import mp.dao.UserDAO;
import mp.model.User;
import mp.model.CommonUser;
import mp.model.VIPUser;

/**
 * Tela de gerenciamento de usuários
 *
 * @author Edivânia Pontes (edivaniap@ufrn.edu.br)
 * @author Anne Ílary (ilarymoraes@hotmail.com)
 * @since 24 de junho de 2018
 */
public class JFUsers extends javax.swing.JFrame {

    private UserDAO userDAO = null;
    private DefaultTableModel tableModel = null;
    private User userLoggedIn = null;
    String currentSelectedUser = null;

    /**
     * Creates new form JFCadastrarUsuario
     */
    public JFUsers() {
        initComponents();
        setDetails();
        loadUsersOnJTable();
        clearCadastro();
    }

    /**
     * Creates new form JFCadastrarUsuario
     */
    public JFUsers(User usuario) {
        initComponents();
        setDetails();
        loadUsersOnJTable();
        clearCadastro();
        userLoggedIn = usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelCadastro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextName = new javax.swing.JTextField();
        jCheckBoxVIP = new javax.swing.JCheckBox();
        jTextUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jPasswordFieldConfirm = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jButtonEnter = new javax.swing.JButton();
        jLabelTitleAttach = new javax.swing.JLabel();
        jButtonCancel = new javax.swing.JButton();
        jLabelMessageErros = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsers = new javax.swing.JTable();
        jLabelTitulo = new javax.swing.JLabel();
        jButtonAdd = new javax.swing.JButton();
        jButtonRemov = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jLabelMessageActions = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gem Music Player - Cadastrar usuário");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanelCadastro.setBackground(new java.awt.Color(102, 153, 0));
        jPanelCadastro.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome");

        jTextName.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTextName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNameActionPerformed(evt);
            }
        });

        jCheckBoxVIP.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jCheckBoxVIP.setText("VIP");

        jTextUsername.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("User");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Senha");

        jPasswordField.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });

        jPasswordFieldConfirm.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Confirmar senha");

        jButtonEnter.setBackground(new java.awt.Color(153, 204, 0));
        jButtonEnter.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButtonEnter.setForeground(new java.awt.Color(51, 51, 51));
        jButtonEnter.setText("Cadastrar/Editar");
        jButtonEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnterActionPerformed(evt);
            }
        });

        jLabelTitleAttach.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabelTitleAttach.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitleAttach.setText("Titulo...");

        jButtonCancel.setBackground(new java.awt.Color(255, 51, 51));
        jButtonCancel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButtonCancel.setForeground(new java.awt.Color(51, 51, 51));
        jButtonCancel.setText("Cancelar");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jLabelMessageErros.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelMessageErros.setForeground(new java.awt.Color(255, 0, 51));
        jLabelMessageErros.setText("mensagem...");

        javax.swing.GroupLayout jPanelCadastroLayout = new javax.swing.GroupLayout(jPanelCadastro);
        jPanelCadastro.setLayout(jPanelCadastroLayout);
        jPanelCadastroLayout.setHorizontalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextUsername)
                                    .addComponent(jTextName, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBoxVIP))
                            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPasswordFieldConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMessageErros)))
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabelTitleAttach)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanelCadastroLayout.setVerticalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabelTitleAttach)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxVIP))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordFieldConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(56, 56, 56)))
                .addComponent(jButtonEnter)
                .addGap(18, 18, 18)
                .addComponent(jButtonCancel)
                .addGap(51, 51, 51)
                .addComponent(jLabelMessageErros)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTableUsers.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTableUsers.setForeground(new java.awt.Color(102, 153, 0));
        jTableUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Usuário", "Tipo"
            }
        ));
        jScrollPane1.setViewportView(jTableUsers);

        jLabelTitulo.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp/view/icons/if_gem.png"))); // NOI18N
        jLabelTitulo.setText("Usuários");

        jButtonAdd.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp/view/icons/if_plus.png"))); // NOI18N
        jButtonAdd.setToolTipText("Adicionar novo usuário");
        jButtonAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonRemov.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRemov.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp/view/icons/if_minus.png"))); // NOI18N
        jButtonRemov.setToolTipText("Remover usuário selecionado");
        jButtonRemov.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRemov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemovActionPerformed(evt);
            }
        });

        jButtonEdit.setBackground(new java.awt.Color(255, 255, 255));
        jButtonEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp/view/icons/if_edit.png"))); // NOI18N
        jButtonEdit.setToolTipText("Editar usuário selecionado");
        jButtonEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jLabelMessageActions.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelMessageActions.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMessageActions.setText("mensagem...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelMessageActions)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRemov, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTitulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jPanelCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelTitulo)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonRemov)
                        .addComponent(jButtonAdd)
                        .addComponent(jButtonEdit))
                    .addComponent(jLabelMessageActions))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNameActionPerformed

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        clearCadastro();
        jLabelTitleAttach.setText("Cadastrar usuário");
        jButtonEnter.setText("Cadastrar");
        jPanelCadastro.setVisible(true);
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonRemovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemovActionPerformed
        jLabelMessageActions.setVisible(false);

        //o index vai indicar o numero da linha que deve ser exluida
        //getSelectedRow() : Returns the index of the first selected row, -1 if no row is selected.
        int selectedRowIndex = jTableUsers.getSelectedRow();

        if (selectedRowIndex != -1) {
            userDAO.delete(selectedRowIndex);
            loadUsersOnJTable();
            jLabelMessageActions.setText("Usuário excluido com sucesso");
        } else {
            jLabelMessageActions.setText("Selecione um usuário para excluir");
        }
        jLabelMessageActions.setVisible(true);
    }//GEN-LAST:event_jButtonRemovActionPerformed

    private void jButtonEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnterActionPerformed
        jLabelMessageErros.setVisible(false);
        jLabelMessageActions.setVisible(false);

        boolean isUnfilled = jTextUsername.getText().equals("") || jTextUsername.getText().equals("")
                || jPasswordField.getText().equals("") || jPasswordFieldConfirm.getText().equals("");

        boolean passwordConfirmation = jPasswordField.getText().equals(jPasswordFieldConfirm.getText());

        boolean alreadyExistUser = userDAO.alreadyExist(jTextUsername.getText());

        if (isUnfilled) {
            jLabelMessageErros.setText("Preencha todos os campos");
            jLabelMessageErros.setVisible(true);
        } else if (!passwordConfirmation) {
            jLabelMessageErros.setText("As senhas não correspondem");
            jLabelMessageErros.setVisible(true);
        } else if (alreadyExistUser) {
            jLabelMessageErros.setText("Já temos alguém usando este usuário");
            jLabelMessageErros.setVisible(true);
        } else {
            User user;
            
            if (jCheckBoxVIP.isSelected()) {
                user = new VIPUser(jTextName.getText(), jTextUsername.getText(), jPasswordField.getText());
            } else {
                user = new CommonUser(jTextName.getText(), jTextUsername.getText(), jPasswordField.getText());
            }

            if (jButtonEnter.getText().equals("Cadastrar")) {
                userDAO.insert(user);
                jLabelMessageActions.setText("Usuário adicionado com sucesso");
            } else {
                userDAO.edit(user, currentSelectedUser);
                jLabelMessageActions.setText("Usuário editado com sucesso");
            }

            clearCadastro();
            loadUsersOnJTable();
            jLabelMessageActions.setVisible(true);
        }
    }//GEN-LAST:event_jButtonEnterActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        clearCadastro();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        jLabelMessageActions.setVisible(false);
        clearCadastro();

        //getSelectedRow() : Returns the index of the first selected row, -1 if no row is selected.
        int selectedRowIndex = jTableUsers.getSelectedRow();

        if (selectedRowIndex != -1) {
            jLabelTitleAttach.setText("Editar usuário");
            jButtonEnter.setText("Editar");
            jPanelCadastro.setVisible(true);

            userDAO = new UserDAO();
            currentSelectedUser = tableModel.getValueAt(selectedRowIndex, 1).toString();
            String currentType =tableModel.getValueAt(selectedRowIndex, 2).toString();
            String currentPass = userDAO.getPassword(currentSelectedUser);
            

            jTextName.setText(tableModel.getValueAt(selectedRowIndex, 0).toString());
            jTextUsername.setText(tableModel.getValueAt(selectedRowIndex, 1).toString());
            jPasswordField.setText(currentPass);
            jPasswordFieldConfirm.setText(currentPass);
            
            if(currentType.equals("VIP")) {
                jCheckBoxVIP.setSelected(true);
            } else {
                jCheckBoxVIP.setSelected(false);
            }
        } else {
            jLabelMessageActions.setText("Selecione um usuário para editar");
            jLabelMessageActions.setVisible(true);
        }
    }//GEN-LAST:event_jButtonEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFUsers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonEnter;
    private javax.swing.JButton jButtonRemov;
    private javax.swing.JCheckBox jCheckBoxVIP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelMessageActions;
    private javax.swing.JLabel jLabelMessageErros;
    private javax.swing.JLabel jLabelTitleAttach;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCadastro;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JPasswordField jPasswordFieldConfirm;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUsers;
    private javax.swing.JTextField jTextName;
    private javax.swing.JTextField jTextUsername;
    // End of variables declaration//GEN-END:variables

    private void setDetails() {
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icons/if_gem.png")));
        this.getRootPane().setDefaultButton(jButtonEnter);
        jPanelCadastro.setVisible(false);
        jLabelMessageActions.setVisible(false);
        jTableUsers.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tableModel = (DefaultTableModel) jTableUsers.getModel();
        userDAO = new UserDAO();
    }

    private void clearCadastro() {
        jTextName.setText("");
        jTextUsername.setText("");
        jPasswordField.setText("");
        jPasswordFieldConfirm.setText("");
        jCheckBoxVIP.setEnabled(true);
        jCheckBoxVIP.setSelected(false);
        jPanelCadastro.setVisible(false);
        jLabelMessageErros.setVisible(false);
    }

    private void loadUsersOnJTable() {
        ArrayList<User> users = userDAO.list();

        if (!users.isEmpty()) {
            //limpando jTable
            while (tableModel.getRowCount() > 0) {
                tableModel.removeRow(0);
            }

            //adicionando cada linha da lista na jTable
            for (User u : users) {
                tableModel.addRow(new Object[]{
                    u.getName(),
                    u.getUsername(),
                    u.getType()
                });
            }
        }
    }
}
